---
- name: Start deploying
  hosts: webservers
  sudo: yes
  sudo_user: root
  remote_user: root
  vars_files:
    - env_vars/base.yml
  vars:
    - update_apt_cache: yes
  roles:
    - base
    - db
    - web

