system_packages:
  - sudo
  - build-essential
  - ntp
  - htop
  - git
  - libpq-dev
  - supervisor
  - vim
  - sshpass

  # Python Dev
  - python-dev
  - python3-dev
  - python-setuptools
  - python3-setuptools
  - python-pip
  - python3-pip
  - python-virtualenv
  - python3-pycurl
