- name: Install database packages
  sudo: yes
  apt: pkg={{ item }}
      state=installed
      update_cache=yes
  with_items: db_packages

- name: Allow password authentication for local socket users
  sudo: yes
  copy: src=pg_hba.conf
        dest=/etc/postgresql/{{ pg_version }}/main/pg_hba.conf
        force=yes
  notify:
      - Restart Postgres

- name: Create Database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{ db_name }}
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'
                 state=present
                 # state=absent

- name: Create User
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{ db_user }}
                    password={{ db_password }}
                    role_attr_flags=SUPERUSER,CREATEDB
                    state=present

- name: Provide user with DB permissions
  sudo: yes
  sudo_user: postgres
  postgresql_user: user={{ db_user }}
                    db={{ db_name }}
                    priv=ALL
